// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package database

import ()

type Client struct {
	ID           int32  `json:"id"`
	Name         string `json:"name"`
	ClientTypeID int64  `json:"client_type_id"`
	TaxCode      string `json:"tax_code"`
	Address      string `json:"address"`
	PhoneNumber  string `json:"phone_number"`
}

type ClientType struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}
